// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ltDheLMmdZF_ndxAknqtFCx8WdsPDFc',
    appId: '1:474148614863:web:1e3c16eccd392a7f163dba',
    messagingSenderId: '474148614863',
    projectId: 'pizzamellisos',
    authDomain: 'pizzamellisos.firebaseapp.com',
    databaseURL: 'https://pizzamellisos-default-rtdb.firebaseio.com',
    storageBucket: 'pizzamellisos.appspot.com',
    measurementId: 'G-0HS3HTWP6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAG2lWPqOA_UOb1UG2C7YIMUola-xiGs',
    appId: '1:474148614863:android:d4a2d1dc9a242f86163dba',
    messagingSenderId: '474148614863',
    projectId: 'pizzamellisos',
    databaseURL: 'https://pizzamellisos-default-rtdb.firebaseio.com',
    storageBucket: 'pizzamellisos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq4r0940dyObfo2w-jrcGSJ-bW1COadXE',
    appId: '1:474148614863:ios:302bb7ed27411fc5163dba',
    messagingSenderId: '474148614863',
    projectId: 'pizzamellisos',
    databaseURL: 'https://pizzamellisos-default-rtdb.firebaseio.com',
    storageBucket: 'pizzamellisos.appspot.com',
    iosClientId: '474148614863-l5iq5af8qnd88033d1j1dqk8td8kqhdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPizzeria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq4r0940dyObfo2w-jrcGSJ-bW1COadXE',
    appId: '1:474148614863:ios:302bb7ed27411fc5163dba',
    messagingSenderId: '474148614863',
    projectId: 'pizzamellisos',
    databaseURL: 'https://pizzamellisos-default-rtdb.firebaseio.com',
    storageBucket: 'pizzamellisos.appspot.com',
    iosClientId: '474148614863-l5iq5af8qnd88033d1j1dqk8td8kqhdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.appPizzeria',
  );
}
